export const ARTICLE_FETCH = 'ARTICLE_FETCH';
export const ARTICLE_FETCH_RESULT = 'ARTICLE_FETCH_RESULT';

export const ARTICLES_FETCH = 'ARTICLES_FETCH';
export const ARTICLES_FETCH_RESULT = 'ARTICLES_FETCH_RESULT';
export const ARTICLES_SET_FILTER = 'ARTICLES_SET_FILTER';
export const ARTICLES_SET_FILTER_RESULT = 'ARTICLES_SET_FILTER_RESULT';
export const ARTICLES_FETCH_ERROR = 'ARTICLES_FETCH_ERROR';